# Generated by Django 5.2.6 on 2025-09-15 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlockDumperExecution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("block_number", models.PositiveIntegerField(db_index=True, unique=True)),
                ("total_tasks_scheduled", models.PositiveBigIntegerField(default=0)),
                ("tasks_completed", models.PositiveBigIntegerField(default=0)),
                ("tasks_failed", models.PositiveBigIntegerField(default=0)),
                ("tasks_pending", models.PositiveBigIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("all_completed", models.BooleanField(default=False)),
                ("has_failures", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Execution",
                "verbose_name_plural": "Executions",
            },
        ),
        migrations.CreateModel(
            name="BlockDumperConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "function_path",
                    models.CharField(help_text="Path to the executable function: myapp.task.function", max_length=255),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("every_block", "Every Block"),
                            ("modulo", "Modulo Condition"),
                            ("custom", "Custom Function"),
                            ("epoch_start", "Epoch Start"),
                            ("epoch_middle", "Epoch Middle"),
                            ("epoch_end", "Epoch End"),
                        ],
                        default="every_block",
                        max_length=20,
                    ),
                ),
                ("condition_params", models.JSONField(blank=True, default=dict)),
                (
                    "netuid_type",
                    models.CharField(
                        choices=[
                            ("none", "No Netuid"),
                            ("all", "All Netuids"),
                            ("single", "Single Netuid"),
                            ("multiple", "Multiple Netuids"),
                        ],
                        default="none",
                        max_length=15,
                    ),
                ),
                ("netuid_values", models.JSONField(blank=True, default=list)),
                ("queue", models.CharField(default="celery", max_length=70)),
                ("max_retries", models.PositiveIntegerField(default=5)),
                ("retry_backoff", models.PositiveIntegerField(default=2)),
                ("timeout", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_executions", models.PositiveIntegerField(default=0)),
                ("successful_executions", models.PositiveIntegerField(default=0)),
                ("failed_executions", models.PositiveIntegerField(default=0)),
                ("last_execution_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Configuration",
                "verbose_name_plural": "Configurations",
                "indexes": [
                    models.Index(fields=["is_active", "condition_type"], name="abstract_bl_is_acti_5ba7a4_idx"),
                    models.Index(fields=["queue", "is_active"], name="abstract_bl_queue_821448_idx"),
                    models.Index(fields=["last_execution_at"], name="abstract_bl_last_ex_42d9b5_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScheduledTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("block_number", models.IntegerField(db_index=True)),
                ("netuid", models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ("celery_task_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("scheduled_time", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("max_retries_reached", models.BooleanField(default=False)),
                ("last_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("execution_duration", models.DurationField(blank=True, null=True)),
                ("result_data", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_tasks",
                        to="abstract_block_dumper.blockdumperconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Task",
                "verbose_name_plural": "Scheduled Tasks",
            },
        ),
    ]
