# Generated by Django 5.2.6 on 2026-08-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("abstract_block_dumper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskattempt",
            name="celery_queue_override",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
